import Vue from 'vue';
export const CLOSE_EDIT = 'close-edit';
export const CLOSE_DETAILS = 'close-details';
export const MOVE_CARD = 'move-card';
export const COPY_CARD = 'copy-card';
export const SAVE_BOARD = 'save-board';
export const SAVE_MEMBERS = 'save-members';
export const DELETE_CARD = 'delete-card';
export const COPY_LIST = 'copy-list';
export const MOVE_LIST = 'move-list';
export const SAVE_LIST = 'move-list';
export const eventBus = new Vue();